export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';

export const REGISTER_SUCESS = 'REGISTER_SUCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const GET_USER = 'GET_USER';
export const LOGIN_SUCESS = 'LOGIN_SUCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';

// Types for Redux
export const ADD_PURCHASE = 'ADD_PURCHASE';
export const ADD_PURCHASE_SUCESS = 'ADD_PURCHASE_SUCESS';
export const ADD_PURCHASE_ERROR = 'ADD_PURCHASE_ERROR ';

export const GET_PURCHASE = 'GET_PURCHASE';
export const GET_PURCHASE_SUCESS = 'GET_PURCHASE_SUCESS';
export const GET_PURCHASE_ERROR = 'GET_PURCHASE_ERROR';

export const DELETE_PURCHASE = 'DELETE_PURCHASE';
export const DELETE_PURCHASE_SUCESS = 'DELETE_PURCHASE_SUCESS';
export const DELETE_PURCHASE_ERROR = 'DELETE_PURCHASE_ERROR';
